language: ruby
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0
sudo: false
before_install:
  - gem update --system # https://github.com/travis-ci/travis-ci/issues/8978#issuecomment-354036443
  - gem install bundler # https://github.com/travis-ci/travis-ci/issues/9333#issuecomment-373042916
script: "./bin/travis_script.sh"
