version: 1.0.{build}

skip_tags: true

environment:
  matrix:
    - RUBY_VERSION: "24-x64"
    - RUBY_VERSION: "24"
    - RUBY_VERSION: "25-x64"
    - RUBY_VERSION: "25"

install:
  - SET PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundler env
  - bundle install

test_script:
  - bundle exec rspec

build: off
